# Site Configuration
title: e-State Real Store
description: Your premier real estate affiliate platform for discovering curated properties and real estate resources.
author: e-State Real Store
email: contact@estatereal.com
url: "https://e-statereal.github.io/shop" # Replace with your actual GitHub Pages URL
baseurl: "" # Leave empty if using custom domain

# Collections Configuration
collections:
  pages:
    output: true
    permalink: /:collection/:name/

# Navigation Configuration
navigation:
  education:
    - title: "Get Started"
      url: "/pages/get-started.html"
      icon: "fas fa-rocket"
    - title: "Enroll Now"
      url: "/pages/enroll.html"
      icon: "fas fa-user-plus"
    - title: "Register"
      url: "/pages/register.html"
      icon: "fas fa-user-edit"
  properties:
    - title: "Contact Agent"
      url: "/pages/contact.html"
      icon: "fas fa-phone"
    - title: "Schedule Visit"
      url: "/pages/schedule.html"
      icon: "fas fa-calendar-alt"

# Educational Materials Configuration
educational_materials:
  a1b2c3d4-e5f6-7890-abcd-ef1234567890:
    title: "Premium Real Estate Course"
    type: "course"
    price: "$997"
    original_price: "$1,497"
    duration: "12 weeks"
    description: "Master the fundamentals of real estate investment, market analysis, and property management through our expert-led curriculum."
    features:
      - "Market Analysis: Understanding local and global real estate trends"
      - "Investment Strategies: From fix-and-flip to long-term rentals"
      - "Property Valuation: Accurate pricing and appraisal techniques"
      - "Legal Framework: Contracts, regulations, and compliance"
      - "Financing Options: Mortgages, loans, and creative financing"
      - "Portfolio Management: Building and scaling your real estate empire"
  
  b2c3d4e5-f6g7-8901-bcde-f23456789012:
    title: "Investment Strategies Webinar"
    type: "webinar"
    price: "Free"
    duration: "90 minutes"
    date: "December 15, 2024"
    time: "7:00 PM EST"
    description: "Join industry experts for an exclusive live session on advanced real estate investment strategies."
    features:
      - "Market Timing: When to buy, sell, or hold properties"
      - "Risk Management: Protecting your investments in volatile markets"
      - "Tax Strategies: Maximizing deductions and minimizing liabilities"
      - "Technology Integration: Using AI and data analytics for better decisions"

# Properties Configuration
properties:
  c3d4e5f6-g7h8-9012-cdef-345678901234:
    title: "Downtown Loft Opportunity"
    type: "investment"
    price: "$450,000"
    location: "Downtown Business District"
    size: "1,200 sq ft"
    bedrooms: 2
    bathrooms: 2
    year_built: 2018
    condition: "Excellent"
    roi: "8-12% annually"
    monthly_rent: "$3,200 - $3,800"
    description: "Prime location loft with exceptional ROI potential and modern amenities."
    amenities:
      - "Modern kitchen with stainless steel appliances"
      - "Hardwood floors throughout"
      - "Large windows with city views"
      - "In-unit laundry"
      - "Secure building access"
    market_analysis: "This property is located in a rapidly appreciating neighborhood with strong rental demand from young professionals and small families."
  
  d4e5f6g7-h8i9-0123-defg-456789012345:
    title: "Luxury Beachfront Villa"
    type: "luxury"
    price: "$2,850,000"
    location: "Exclusive Beachfront Community"
    size: "4,500 sq ft"
    bedrooms: 5
    bathrooms: 4.5
    year_built: 2020
    condition: "Like New"
    roi: "6-9% annually"
    monthly_rent: "$15,000 - $25,000"
    description: "Exclusive beachfront property offering the ultimate in luxury living and investment potential."
    amenities:
      - "Infinity pool with ocean views"
      - "Chef's kitchen with premium appliances"
      - "Home theater and wine cellar"
      - "Private beach access"
      - "Smart home technology"
      - "3-car garage"
    market_analysis: "This luxury villa offers both personal enjoyment and excellent rental income potential, especially during peak tourist seasons."

# Email Configuration
email_config:
  from: "noreply@estatereal.com"
  to: "contact@estatereal.com"
  subject_prefix: "[e-State Real Store]"

# Theme Configuration
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# SEO and Meta Tags
lang: en
encoding: utf-8
highlighter: rouge
permalink: pretty

# Social Media and Contact
social:
  name: e-State Real Store
  links:
    - https://instagram.com/e_state_real
    - https://facebook.com/E-StateReal
    - https://linkedin.com/in/e-StateReal
    - https://x.com/e_state_real
    - https://www.tiktok.com/@estate.real

# Plugins and Extensions (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - src/
  - scripts/
  - _config.dev.yml
  - DEVELOPMENT.md

# Include files that should be processed
include:
  - _posts
  - assets
  - images

# Timezone
timezone: America/New_York

# Future posts
future: false

# Show drafts
show_drafts: false

# Keep files
keep_files: [assets, images, _config.yml]

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass settings
sass:
  style: compressed
  load_paths:
    - _sass
